# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unregistereddish',
            old_name='detectionTime',
            new_name='detection_time',
        ),
    ]
