# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_auto_20160210_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishchore',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
