# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 19:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_auto_20160210_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishchore',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_dish_chores', to=settings.AUTH_USER_MODEL),
        ),
    ]
