# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160209_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='valid_key',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
