# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160210_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='valid_key_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='is_absent_since',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
