# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160212_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='valid_key_date',
            new_name='valid_key_time',
        ),
    ]
