# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hwid', models.CharField(max_length=8, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('one_time_pad', models.CharField(max_length=32)),
                ('is_pad_used', models.BooleanField()),
                ('pad_expires', models.DateTimeField()),
            ],
        ),
    ]
