# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 10:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chores', '__first__'),
        ('hardware', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.Hardware')),
                ('is_in_use', models.BooleanField(default=False)),
                ('last_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('hardware.hardware',),
        ),
        migrations.CreateModel(
            name='ApplianceChore',
            fields=[
                ('chore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chores.Chore')),
                ('appliance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appliances.Appliance')),
            ],
            bases=('chores.chore',),
        ),
    ]
