# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 20:54
from __future__ import unicode_literals

import chores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_auto_20160210_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringchore',
            name='round_robin',
            field=models.CharField(blank=True, default=chores.models.random_order, max_length=50, null=True),
        ),
    ]
